import type { WorkOrder } from '@/types';

export const workOrders: WorkOrder[] = [
  {
    id: 'OT-2026-0847',
    title: 'Inspection vibratoire de la pompe P-101A',
    unit: 'Topping / Train 1',
    service: 'Machines tournantes',
    priority: 'Haute',
    status: 'En cours',
    assignee: 'K. Hamidi',
    startDate: '08 sept. 2026',
    dueDate: '10 sept. 2026',
    progress: 68,
    equipment: 'P-101A',
    permit: 'PT-2026-118',
    agents: 2,
    description: 'Analyse vibratoire complète de la pompe P-101A (palier avant / palier arrière) suite à une hausse d’amplitude observée sur le quart du matin. Contrôler l’alignement, l’état des roulements et le graissage.',
    observation: 'Intervention sous Permis de Travail. Consignation électrique et isolation process à confirmer avec le chef de quart avant démontage.',
  },
  {
    id: 'OT-2026-0846',
    title: 'Remplacement joint vanne XV-204',
    unit: 'Hydrotraitement',
    service: 'Mécanique',
    priority: 'Critique',
    status: 'En attente',
    assignee: 'S. Belkacem',
    startDate: '09 sept. 2026',
    dueDate: '09 sept. 2026',
    progress: 0,
    equipment: 'XV-204',
    permit: 'PT-2026-112',
    agents: 3,
    description: 'Fuite au joint de la vanne XV-204. Remplacer le joint, contrôler les portées de bride et effectuer un test d’étanchéité après remontage.',
    observation: 'Pièce de rechange disponible au magasin atelier mécanique. Zone ATEX : outillage antidéflagrant obligatoire.',
  },
  {
    id: 'OT-2026-0842',
    title: 'Calibration transmetteurs pression',
    unit: 'Reforming catalytique',
    service: 'Instrumentation',
    priority: 'Normale',
    status: 'En cours',
    assignee: 'M. Zerrouki',
    startDate: '07 sept. 2026',
    dueDate: '12 sept. 2026',
    progress: 42,
    equipment: 'PT-331 / PT-334 / PT-338',
    permit: 'PT-2026-109',
    agents: 2,
    description: 'Étalonnage des transmetteurs de pression PT-331, PT-334 et PT-338. Vérifier la boucle 4-20 mA, ajuster le zéro et consigner les écarts dans le rapport d’instrumentation.',
    observation: 'Calibreur et manomètre étalon à retirer au laboratoire instrumentation avant 07:30.',
  },
  {
    id: 'OT-2026-0838',
    title: 'Contrôle thermographique armoire HT',
    unit: 'Utilités / Électricité',
    service: 'Électricité',
    priority: 'Haute',
    status: 'Terminé',
    assignee: 'A. Merouane',
    startDate: '05 sept. 2026',
    dueDate: '07 sept. 2026',
    progress: 100,
    equipment: 'Armoire HT-04',
    permit: 'PT-2026-101',
    agents: 2,
    description: 'Inspection thermographique de l’armoire HT-04. Relever les points chauds sur jeux de barres, disjoncteurs et raccordements, puis comparer aux seuils de consigne.',
    observation: 'Intervention clôturée. Rapport joint au dossier OT. Aucune anomalie critique détectée.',
  },
  {
    id: 'OT-2026-0831',
    title: 'Révision préventive compresseur C-04',
    unit: 'Utilités',
    service: 'Machines tournantes',
    priority: 'Normale',
    status: 'En retard',
    assignee: 'Y. Djebbar',
    startDate: '02 sept. 2026',
    dueDate: '08 sept. 2026',
    progress: 76,
    equipment: 'C-04',
    permit: 'PT-2026-097',
    agents: 4,
    description: 'Révision préventive du compresseur C-04 : contrôle des soupapes, vidange d’huile, inspection des filtres et serrage des liaisons process.',
    observation: 'Retard dû à l’indisponibilité d’un joint d’huile. Livraison magasin prévue le 11 sept. 2026.',
  },
  {
    id: 'OT-2026-0827',
    title: 'Mise en conformité ligne vapeur',
    unit: 'Parc utilités',
    service: 'Tuyauterie',
    priority: 'Haute',
    status: 'Terminé',
    assignee: 'Équipe quart A',
    startDate: '01 sept. 2026',
    dueDate: '06 sept. 2026',
    progress: 100,
    equipment: 'Ligne vapeur LV-12',
    permit: 'PT-2026-088',
    agents: 5,
    description: 'Mise en conformité de la ligne vapeur LV-12 : remplacement des supports dégradés, reprise d’isolation et contrôle visuel des soudures.',
    observation: 'Travaux réceptionnés par le superviseur utilités. Isolation thermique refaite sur 18 ml.',
  },
];

export const activity = [
  { time: '09:42', title: 'OT-2026-0847 mis à jour', detail: 'Progression portée à 68% · K. Hamidi', tone: 'orange' },
  { time: '09:18', title: 'Permis de travail validé', detail: 'Hydrotraitement · PT-2026-112', tone: 'green' },
  { time: '08:55', title: 'Nouvelle anomalie signalée', detail: 'Vibration anormale · Pompe P-101A', tone: 'red' },
  { time: '08:31', title: 'Intervention clôturée', detail: 'Armoire HT · A. Merouane', tone: 'blue' },
];
